server:
  port: 8080
  servlet:
    context-path: /


spring:
  # todo 개발 데이터베이스 연결
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500 #일대다 컬렉션 조회 시 성능 최적화
    open-in-view: false # 영속석 컨텍스트이 생존 범위를 트랜잭션 범위로 한정
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  level:
    org.hibernate.type: trace
    com.app: debug #todo 패키지 수정

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

kakao:
  client:
    id: ENC(4FiqrXuXgOuTKUheOf605wI8o+ApKKqFSKszYm943JqxGQG66bamvv32WMAQjDJf)
    secret: ENC(yoWG9HSNsR6ypXGkfH80364o2/90u/IRQ/crTm0Gj7/iMMm6vpsnQAJJQe2Fb2YH)

token:
  secret: ENC(5UrGEFXTCIjP0mH1Y7yFbFBrJBMMjb2+zIEt2KqDiHN+jpXhQzVCINDfIhEFvbdy) # JWT 생성 시 사용할 임의의 문자열
  access-token-expiration-time: 9000001212  # 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)


jasypt:
  encryptor:
    #password:
    password: ${PASSWORD} #vm option에 추가한 값
